routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use app\Http\Controllers\admin\Auth\AuthenticatedSessionController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


// Route::get('/dashboard','App\\Http\\Controllers\\user\ServiceController@index')->name('dashboard');
Route::resource('/dashboard','App\\Http\\Controllers\\user\\ServiceController')->only(['index','show'])->middleware(['auth']);
// Route::resource('/dashboard/{id}', 'App\\Http\\Controllers\\user\\TicketController')->middleware(['auth']);
Route::resource('/dashboard/ticket', 'App\\Http\\Controllers\\user\\TicketController')->middleware(['auth']);
Route::get('myticket', 'App\\Http\\Controllers\\user\\TicketController@index')->middleware(['auth']);
Route::resource('/comment', 'App\\Http\\Controllers\\user\\CommentController')->middleware(['auth']);
Route::resource('/notification', 'App\\Http\\Controllers\\user\\NotifactionController')->middleware(['auth']);
// User Routes





require __DIR__ . '/auth.php';



// Admin Routes

Route::namespace('App\Http\Controllers\admin')->prefix('admin')->name('admin.')->group(function () {


    Route::namespace('Auth')->middleware('guest:admin')->group(function () {
        // Authentication Routes (Admin)
        Route::get('/login', 'AuthenticatedSessionController@create')->name('login');
        Route::post('/login', 'AuthenticatedSessionController@store')->name('admin_login');
       

    });
    Route::middleware('admin')->group(function () {
        // Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
      
        Route::get('/dashboard', 'HomeController@index')->name('dashboard');
        Route::resource('/services', 'ServiceController');
        Route::resource('/Statuses', 'StatusController');
        Route::resource('/tickte', 'TicketController');
        Route::resource('/comment', 'CommentController');
        
        
        
        
    });
    Route::post('/logout', 'Auth\AuthenticatedSessionController@destroy')->name('logout');
});

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    use HasFactory;
    protected $fillable = ['title', 'description', 'userid', 'serviceid'];

    public function Statuses()
    {
        return $this->belongsTo('App\Models\Status', 'statusid');
    }
    public function comments()
    {
        return $this->hasMany('App\Models\Comment');
    }
    public function users()
    {
        return $this->belongsTo('App\Models\User', 'userid');
    }
    public function services()
    {
        return $this->belongsTo('App\Models\Service', 'serviceid');
    } 
}

app/Http/Controllers/admin/TicketController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\TikectStore;
use App\Models\comment;
use App\Models\Ticket;
use App\Models\Status;

use Illuminate\Support\Facades\Auth;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Tickets = Ticket::with('Statuses')->orderBy('created_at', 'desc')->get();

       
        // dd($Tickets);
        return view('Admin.dashboard', compact('Tickets', 'comments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $comments = Comment::where('ticket_id', $id)->orderBy('created_at', 'desc')->get();



        $ticket = Ticket::with('Comments')->find($id);


        $user = Ticket::with('Users')->find($id);
        $admin = Auth::guard('admin')->user()->name;
        
        
        
     
        return view('Admin.comment.create', compact('ticket','user','admin', 'comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        dd($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $statusid = $request->input('statusid');
        $ticket = Ticket::find($id);
        $ticket->statusid = $statusid;
        $ticket->save();

        
    
        return redirect()->action('admin\TicketController@index')->with('update', 'Ticket updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/user/TicketController.php
<?php

namespace App\Http\Controllers\user;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\TikectStore;
use App\Models\Admin;
use App\Models\Ticket;
use App\Models\Status;
use App\Models\Comment;
use Illuminate\Support\Facades\Auth;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $Tickets = Ticket::with('Statuses')->where('userid', auth()->user()->id)->orderBy('created_at', 'desc')->get();

        // if exists comment in the comments table have check_is_finsh = 1 change the status to 2
        // foreach ($Tickets as $Ticket) {
        //     $comments = Comment::where('ticket_id', $Ticket->id)->where('check_is_finsh', 1)->get();
        //     if (count($comments) > 0) {
        //         $Ticket->statusid = 3;
        //         $Ticket->update();
        //     }

        // }
        // $comments = comment::where('is_admin', 1)->orderBy('created_at', 'desc')->get();
        // $notification = $comments->count();

        // dd(strtotime('-1 heure'));
        $comments = Comment::where('is_admin', 1)->where('created_at', '>', date('Y-m-d H:i:s', strtotime('1 heure')))->orderBy('created_at', 'desc')->get();
        $notification = $comments->count();
        

        
            // multiple return

            
       

 
        return view('ticket.index', compact('Tickets', 'comments', 'notification'));
    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        dd('ticket.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TikectStore $request)
    {
        // access the message session


        $title = $request->input('title');
        $description = $request->input('description');
        $statusid = $request->input('statusid');
        $userid = auth()->user()->id;
        $serviceid = $request->input('serviceid');
        $statusid = 1;
   $data = [
        'title' => $title,
        'description' => $description,
        'statusid' => $statusid,
        'userid' => $userid,
        'serviceid' => $serviceid,
        'statusid' => $statusid,
    ];
   

        
      Ticket::create($data);
        
       
        return redirect()->action('user\TicketController@index')->with('addcomment', 'Ticket created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $commentsadmin = comment::where('ticket_id', $id)->where('is_admin', 1)->orderBy('created_at', 'desc')->get();
        // // dd($commentsadmin);
        // $commentsuser = comment::where('ticket_id', $id)->where('is_admin', 0)->orderBy('created_at', 'desc')->get();
        
        $comments = Comment::where('ticket_id', $id)->orderBy('created_at', 'desc')->get();

        $admin = Admin::find(1)->name;
      
        $commentsadmin = Comment::where('ticket_id', $id)->where('is_admin', 1)->orderBy('created_at', 'desc')->get();
        //  if exitsts admin comments update statusid to 2
        
        if ($commentsadmin->count() > 0) {
            $ticket = Ticket::find($id);
            $ticket->statusid = 2;
            $ticket->save();
        }
        // if exists admin comments update statusid to 3
        if ($commentsadmin->count() > 0) {
        //    check is_finish = 1 in the comments user
            $commentsuser = Comment::where('ticket_id', $id)->where('is_admin', 0)->where('check_is_finsh', 1)->get();
            if ($commentsuser->count() > 0) {
                $ticket = Ticket::find($id);
                $ticket->statusid = 3;
                $ticket->save();
            }

           
        }
        

        

        
        
    
        $ticket = Ticket::with('Comments')->find($id);

        


        $user = Ticket::with('Users')->find($id);

        return view('comment.create', compact('ticket', 'user', 'admin', 'comments'));
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ticket = Ticket::with('services')->find($id);
    
        return view('ticket.edit', compact('ticket'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Ticket::find($id)->update($request->all());
        return redirect()->action('user\TicketController@index')->with('update', 'Ticket updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Ticket::destroy($id);
        return redirect()->action('user\TicketController@index')->with('deletcomment', 'Ticket deleted!');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/ticket/create.blade.php
<x-app-layout>
  <x-slot name="header">
     @if ($errors->any())
    <div>
        <div class="font-medium text-red-600">
            {{ __('Whoops! Something went wrong.') }}
        </div>

        <ul class="mt-3 list-disc list-inside text-sm text-red-600">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
    </x-slot>

<div class="heading text-center font-bold text-2xl  text-gray-800">New Post</div>
<style>
  body {background:white !important;}
  
</style>

<form method="post" action="{{route('ticket.store')}}">
    @csrf
  <div class="editor mx-auto w-10/12 flex flex-col text-gray-800 border border-gray-300 p-4 shadow-lg max-w-2xl">
    
    <p class="title bg-gray-100 border border-gray-300 p-2 mb-4 outline-none" spellcheck="false" placeholder="Title" type="text">
    {{$card->title}}
    </p>  
 

    <input type="hidden" name="serviceid" value="{{ $card->id }}">
    <input type="hidden" name="userid" value="{{Auth::user()->id}}">
    <input name="title" class="title bg-gray-100 border border-gray-300 p-2 mb-4 outline-none" spellcheck="false" placeholder="Title" type="text">
    <textarea name="description" id="editor" class="description bg-gray-100 sec p-3 h-60 border border-gray-300 outline-none" spellcheck="false" placeholder="Describe everythnig about this Content her"></textarea>
    
    <!-- icons -->
    
    <!-- buttons -->
    <div class="buttons flex">
      <a  class="btn border border-gray-300 p-1 px-4 font-semibold cursor-pointer text-gray-500 ml-auto">Cancel</a>
      <button class="btn border border-indigo-500 p-1 px-4 font-semibold cursor-pointer text-gray-200 ml-2 bg-indigo-500">Create</button>
    </div>
</form>
</div>
</x-app-layout>


 <script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>

resources/views/ticket/edit.blade.php
<x-app-layout>
  <x-slot name="header">
     @if ($errors->any())
    <div>
        <div class="font-medium text-red-600">
            {{ __('Whoops! Something went wrong.') }}
        </div>

        <ul class="mt-3 list-disc list-inside text-sm text-red-600">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
    </x-slot>

<div class="heading text-center font-bold text-2xl  text-gray-800">New Post</div>
<style>
  body {background:white !important;}
  
</style>

<form method="post" action="{{route('ticket.update', $ticket->id)}}">
    @csrf
    @method('PUT')
  <div class="editor mx-auto w-10/12 flex flex-col text-gray-800 border border-gray-300 p-4 shadow-lg max-w-2xl">
    
    <p class="title bg-gray-100 border border-gray-300 p-2 mb-4 outline-none" spellcheck="false" placeholder="Title" type="text">
    {{ $ticket->services->title }}
    </p>  
 

    <input type="hidden" name="serviceid" value="{{$ticket->services->id }}">
    <input type="hidden" name="userid" value="{{Auth::user()->id}}">
    <input name="title" class="title bg-gray-100 border border-gray-300 p-2 mb-4 outline-none" spellcheck="false" placeholder="Title" type="text" value="{{ $ticket->title }}">
    <textarea name="description" id="editor" class="description bg-gray-100 sec p-3 h-60 border border-gray-300 outline-none" spellcheck="false" placeholder="Describe everythnig about this Content her">
        {{ $ticket->description }}
    </textarea>
    
    <!-- icons -->
    
    <!-- buttons -->
    <div class="buttons flex">
      <a  class="btn border border-gray-300 p-1 px-4 font-semibold cursor-pointer text-gray-500 ml-auto">Cancel</a>
      <button class="btn border border-indigo-500 p-1 px-4 font-semibold cursor-pointer text-gray-200 ml-2 bg-indigo-500">Create</button>
    </div>
</form>
</div>
</x-app-layout>


 <script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>

resources/views/ticket/index.blade.php
<x-app-layout>
   <x-slot name="header">
      See Notification
   <a href="{{route('notification.index')}}" class="">   
           <span class="relative inline-block">
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" class="sc-15iua2v-0 dIfPYi"><path d="M17.333 8.6c0-1.485-.562-2.91-1.562-3.96A5.208 5.208 0 0012 3c-1.415 0-2.771.59-3.771 1.64A5.745 5.745 0 006.667 8.6C6.667 15.133 4 17 4 17h16s-2.667-1.867-2.667-8.4zM14 20a2.186 2.186 0 01-.846.732A2.588 2.588 0 0112 21c-.405 0-.803-.092-1.154-.268A2.186 2.186 0 0110 20" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="colorStroke"></path></svg>  <span class="absolute top-0 right-0 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-red-100 transform translate-x-1/2 -translate-y-1/2 bg-red-600 rounded-full">
{{ $notification }}
  </span>
</span>
   </a>
   </x-slot>



   <div class="flex  shadow-lg rounded-lg mx-52 md:mx-auto  ">
      @include('Admin.layouts.message')
   </div>

   @if (count($Tickets) <= 0) <div v-if="Appointments.length <=0">

      <div class="flex items-center justify-center ">
         <div class="px-4 lg:py-12">
            <div class="lg:gap-4 lg:flex">
               <div class="flex flex-col items-center justify-center md:py-24 lg:py-32">
                  <h1 class="mb-8 font-bold text-blue-600 text-5xl">No Tickets</h1>
                  <p class="mb-8 text-2xl font-bold text-center text-gray-800 md:text-3xl">
                     <span class="text-red-500">Oops!</span> You don't have any Tickets yet.
                  </p>

                  <a href="{{ route('dashboard.index')}}"
                     class="px-6 py-2 text-sm font-semibold text-blue-800 bg-blue-100">Create One
                  </a>
               </div>
            </div>
         </div>
      </div>
      @endif

      <!-- post card -->
      @foreach ($Tickets as $ticket)

      <div class="flex bg-white shadow-lg rounded-lg mx-52 md:mx-auto  mt-5 max-w-md md:max-w-2xl  ">
         <!--horizantil margin is just for display-->
         <div class="flex items-start px-4 py-4 pt-0 ">

            <img class="w-12 h-12 rounded-full object-cover mr-4 shadow"
               src="https://images.unsplash.com/photo-1542156822-6924d1a71ace?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60"
               alt="avatar">
            <div class="">
               <div class="flex items-center justify-between">
                  <h2 class="text-lg font-semibold text-gray-900 -mt-1">{{ Auth::user()->name }} </h2>
                  <span
                     class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">
                     {{$ticket->statuses->name}}
                  </span>
                  <small class="text-sm text-gray-700">{{ $ticket->created_at->diffForHumans() }}</small>
               </div>
               <p class="text-gray-700"> Joined {{ Auth::user()->created_at->diffForHumans() }}</p>
               <div class="">
                  <h2 class="text-lg font-semibold text-gray-800 -mt-1">{{ $ticket->title }} </h2>
                  <p class="mt-3 text-gray-700 text-sm w-70" style="width: 486px;">
                     {!! html_entity_decode( $ticket->description ) !!}
                     {{-- <img
                        src="https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1361&q=80">
                     --}}
               </div>

               <div class= "mt-3 flex items-center justify-between">
                     <div class="flex items-center">
                        <a href="" class="flex mr-2 text-gray-700 text-sm mr-3 ">
                           <svg fill="none" viewBox="0 0 24 24" class="w-6 h-6 mr-1" stroke="currentColor">
                              <path class=" " stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                 d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                           </svg>
                        </a>
                        <a href={{ route('ticket.show', $ticket->id) }} class="flex text-gray-700 text-sm mr-8">
                           <svg fill="none" viewBox="0 0 24 24" class="w-6 h-6 mr-1" stroke="currentColor">
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                 d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z" />
                           </svg>

                           <samp> {{ $ticket->comments->count() }} comments</samp>
                        </a>
                        </form>
                     </div>  
                     <div class="flex ">
                        <form method="post" action="{{ route('ticket.edit', $ticket->id)}}">
                           @csrf
                           @method('GET')
                        <button type='submit'
                       class="text-xs inline-block py-1 px-2.5 leading-none text-center whitespace-nowrap align-baseline font-bold text-green-500  rounded">Edit</button>
                        </form>
                     <form method="post" action="{{ route('ticket.destroy', $ticket->id) }}">
                        @csrf
                        @method('DELETE')
                       
                      <button type='submit'
                        class="text-xs inline-block py-1 px-2.5 leading-none text-center whitespace-nowrap align-baseline font-bold text-red-500  rounded">Remove</button>
                     </form>
                     </div> 
                  </div>

   
 
{{-- create a @section --}}



              
            </div>
         </div>

      </div>
      @endforeach

</x-app-layout>

<script>

   function CreateComment() {

      document.getElementById('form').style.display = 'block';
   }



</script>