routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use app\Http\Controllers\admin\Auth\AuthenticatedSessionController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


// Route::get('/dashboard','App\\Http\\Controllers\\user\ServiceController@index')->name('dashboard');
Route::resource('/dashboard','App\\Http\\Controllers\\user\\ServiceController')->only(['index','show'])->middleware(['auth']);
// Route::resource('/dashboard/{id}', 'App\\Http\\Controllers\\user\\TicketController')->middleware(['auth']);
Route::resource('/dashboard/ticket', 'App\\Http\\Controllers\\user\\TicketController')->middleware(['auth']);
Route::get('myticket', 'App\\Http\\Controllers\\user\\TicketController@index')->middleware(['auth']);
Route::resource('/comment', 'App\\Http\\Controllers\\user\\CommentController')->middleware(['auth']);
Route::resource('/notification', 'App\\Http\\Controllers\\user\\NotifactionController')->middleware(['auth']);
// User Routes





require __DIR__ . '/auth.php';



// Admin Routes

Route::namespace('App\Http\Controllers\admin')->prefix('admin')->name('admin.')->group(function () {


    Route::namespace('Auth')->middleware('guest:admin')->group(function () {
        // Authentication Routes (Admin)
        Route::get('/login', 'AuthenticatedSessionController@create')->name('login');
        Route::post('/login', 'AuthenticatedSessionController@store')->name('admin_login');
       

    });
    Route::middleware('admin')->group(function () {
        // Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
      
        Route::get('/dashboard', 'HomeController@index')->name('dashboard');
        Route::resource('/services', 'ServiceController');
        Route::resource('/Statuses', 'StatusController');
        Route::resource('/tickte', 'TicketController');
        Route::resource('/comment', 'CommentController');
        
        
        
        
    });
    Route::post('/logout', 'Auth\AuthenticatedSessionController@destroy')->name('logout');
});

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    use HasFactory;
    protected $fillable = ['title','svg'];
    
}

app/Http/Controllers/admin/ServiceController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Service;
use Illuminate\Http\Request;
use App\HTTP\Requests\StoreService;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::all();
        return view('admin.services.index', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreService $request)
    {
        // dd($request->all());
        $data= $request->only(['title','svg']);
        
        Service::create($data);
        return redirect()->route('admin.services.index')->with('success', 'Service created successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $services = Service::find($id);
        return view('admin.services.show', 
        ['services'=>$services]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $service = Service::find($id);
        return view('admin.services.edit', 
        ['service'=>$service]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreService $request, $id)
    {
       
        $service = Service::find($id);
       
        $service->title = $request->title;
        $service->save();
        return redirect()->route('admin.services.index')->with('success', 'Service updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $service = Service::find($id);
        $service->delete();
        return redirect()->route('admin.services.index')->with('delete', 'Service deleted successfully');
    }
}

app/Http/Controllers/user/ServiceController.php
<?php

namespace App\Http\Controllers\user;


use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Service;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cards = Service::all();
        
        return view('dashboard', compact('cards'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // dd('service.show');
        $card = Service::find($id);
        return view('ticket.create', compact('card'));
    }   

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/View/Components/AdminLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AdminLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('admin.layouts.app');
    }
}

resources/views/Admin/services/create.blade.php
<x-admin-layout>

     <x-slot name="header">
       
    </x-slot>

    
    <form method="POST" action= {{route('admin.services.store')}} >
         @csrf
 
         
                
              @include('Admin.layouts.form')
                
                <button type="submit" class=" flex items-center px-4 py-2 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-200 transform bg-blue-700 rounded-md sm:mx-2 hover:bg-blue-600 focus:outline-none focus:bg-blue-600">
                   
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6m0 0v6m0-6h6m-6 0H6" /></svg>          
                    <span>create</span>
                 </button>
                
            </div>
        </div>
    </form>


</x-admin-layout>

resources/views/Admin/services/edit.blade.php
<x-admin-layout>

     <x-slot name="header">
       
    </x-slot>

    
    <form method="POST" action= {{route('admin.services.update',$service->id)}} >
         @csrf
         @method('put')
 
         
                
              @include('Admin.layouts.form')
                
                <button type="submit" class=" flex items-center px-4 py-2 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-200 transform bg-blue-700 rounded-md sm:mx-2 hover:bg-blue-600 focus:outline-none focus:bg-blue-600">
                   
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6m0 0v6m0-6h6m-6 0H6" /></svg>          
                    <span>Update</span>
                 </button>
                
            </div>
        </div>
    </form>


</x-admin-layout>

resources/views/Admin/services/index.blade.php
<x-admin-layout>

     <x-slot name="header">
       
    </x-slot>


@if (count($services) <= 0)
vide 


@else
<div class="w-2/3 mx-auto">





  
  <div class="bg-white shadow-md rounded my-6">
  

    @include('Admin.layouts.message')
    
    
    <table class="text-left w-full border-collapse"> 
      <thead>
        <tr>
          <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">service</th>
          <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Actions</th>
          <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">svg</th>
        </tr>
      </thead>
      <tbody>
    @foreach ($services as $service)
        <tr class="hover:bg-grey-lighter">
          <td class="py-4 px-6 border-b border-grey-light">{{$service['title']}}</td>
          <td class="py-4 px-6 border-b border-grey-light flex ">
            <a href="{{route('admin.services.edit',$service['id'])}}"  id="edite" class="text-grey-lighter font-bold py-1 px-3 rounded text-xs bg-green hover:bg-green-800 ">Edit</a>
            
            <form action= "{{route('admin.services.destroy',$service['id'])}}" method="post" >
              @csrf
              @method('delete')
              <button type="submit" class="text-red-600 font-bold py-1 px-3 rounded text-xs bg-blue hover:bg-blue-dark">delete</button>
            </form>
          </td>
          <td class="py-4 px-6 border-b border-grey-light">
                <div class="w-5 h-5 flex-shrink-0 mr-2 sm:mr-2">
                   {!! html_entity_decode($service['svg']) !!}
               </div>
          </td>
        </tr>
    @endforeach
        
     
       
      </tbody>
    </table>
  </div>
</div>

@endif


</x-admin-layout>