routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use app\Http\Controllers\admin\Auth\AuthenticatedSessionController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


// Route::get('/dashboard','App\\Http\\Controllers\\user\ServiceController@index')->name('dashboard');
Route::resource('/dashboard','App\\Http\\Controllers\\user\\ServiceController')->only(['index','show'])->middleware(['auth']);
// Route::resource('/dashboard/{id}', 'App\\Http\\Controllers\\user\\TicketController')->middleware(['auth']);
Route::resource('/dashboard/ticket', 'App\\Http\\Controllers\\user\\TicketController')->middleware(['auth']);
Route::get('myticket', 'App\\Http\\Controllers\\user\\TicketController@index')->middleware(['auth']);
Route::resource('/comment', 'App\\Http\\Controllers\\user\\CommentController')->middleware(['auth']);
Route::resource('/notification', 'App\\Http\\Controllers\\user\\NotifactionController')->middleware(['auth']);
// User Routes





require __DIR__ . '/auth.php';



// Admin Routes

Route::namespace('App\Http\Controllers\admin')->prefix('admin')->name('admin.')->group(function () {


    Route::namespace('Auth')->middleware('guest:admin')->group(function () {
        // Authentication Routes (Admin)
        Route::get('/login', 'AuthenticatedSessionController@create')->name('login');
        Route::post('/login', 'AuthenticatedSessionController@store')->name('admin_login');
       

    });
    Route::middleware('admin')->group(function () {
        // Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
      
        Route::get('/dashboard', 'HomeController@index')->name('dashboard');
        Route::resource('/services', 'ServiceController');
        Route::resource('/Statuses', 'StatusController');
        Route::resource('/tickte', 'TicketController');
        Route::resource('/comment', 'CommentController');
        
        
        
        
    });
    Route::post('/logout', 'Auth\AuthenticatedSessionController@destroy')->name('logout');
});

app/Models/Status.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    use HasFactory;
    protected $fillable = ['name'];

    
}

app/Http/Controllers/admin/StatusController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\Status;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class StatusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $statuses = Status::all();
        return view('admin.status.index', compact('statuses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.status.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->only(['name']);
        Status::create($data);
        return redirect()->route('admin.Statuses.index')->with('success', 'Status created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $status = Status::find($id);
        return view('admin.status.edit', compact('status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());
        $data = $request->only(['name']);
        Status::find($id)->update($data);
        return redirect()->route('admin.Statuses.index')->with('success', 'Status updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $satus = Status::find($id);
        $satus->delete();
        return redirect()->route('admin.Statuses.index')->with('delete', 'Status deleted successfully');
    }
}

app/View/Components/AdminLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AdminLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('admin.layouts.app');
    }
}

resources/views/Admin/status/create.blade.php
<x-admin-layout>

     <x-slot name="header">
       
    </x-slot>

    
    <form method="POST" action= {{route('admin.Statuses.store')}} >
         @csrf
 
         
                
              @include('Admin.status.form')
                
                <button type="submit" class=" flex items-center px-4 py-2 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-200 transform bg-blue-700 rounded-md sm:mx-2 hover:bg-blue-600 focus:outline-none focus:bg-blue-600">
                   
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6m0 0v6m0-6h6m-6 0H6" /></svg>          
                    <span>create</span>
                 </button>
                
            </div>
        </div>
    </form>


</x-admin-layout>

resources/views/Admin/status/edit.blade.php
<x-admin-layout>

     <x-slot name="header">
       
    </x-slot>

    
    <form method="POST" action= {{route('admin.Statuses.update',$status['id'])}} >
        @csrf
        @method('put')
 
         
                
              @include('Admin.status.form')
                
                <button type="submit" class=" flex items-center px-4 py-2 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-200 transform bg-blue-700 rounded-md sm:mx-2 hover:bg-blue-600 focus:outline-none focus:bg-blue-600">
                   
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6m0 0v6m0-6h6m-6 0H6" /></svg>          
                    <span>Edit</span>
                 </button>
                
            </div>
        </div>
    </form>


</x-admin-layout>

resources/views/Admin/status/form.blade.php
   <div class="max-w-3xl px-6 py-16 mx-auto text-center">
            <h1 class="text-3xl font-semibold text-gray-800 ">Upadte Status</h1>
            <p class="max-w-md mx-auto mt-5 text-gray-500 ">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis, minus tempora nemo quos</p>
@if ($errors->any())
    <div>
        <div class="font-medium text-red-600">
            {{ __('Whoops! Something went wrong.') }}
        </div>

        <ul class="mt-3 list-disc list-inside text-sm text-red-600">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="flex flex-col mt-8 space-y-3 sm:space-y-0 sm:flex-row sm:justify-center sm:-mx-2">
    
    
    <input  name="name" id="" type="text" class="px-4 py-2 text-gray-700  border rounded-md sm:mx-2   dark:border-gray-600 focus:border-blue-400 dark:focus:border-blue-300 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-40" placeholder="name status"  value="{{old('name',$status->name ?? null)}}">

  

resources/views/Admin/status/index.blade.php
<x-admin-layout>

     <x-slot name="header">
       
    </x-slot>


@if (count($statuses) <= 0)
vide 


@else
<div class="w-2/3 mx-auto">





  
  <div class="bg-white shadow-md rounded my-6">
  

    @include('Admin.layouts.message')
    
    
    <table class="text-left w-full border-collapse"> 
      <thead>
        <tr>
          <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">service</th>
          <th class="py-4 px-6 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">Actions</th>
     
        </tr>
      </thead>
      <tbody>
    @foreach ($statuses as $status)
        <tr class="hover:bg-grey-lighter">
          <td class="py-4 px-6 border-b border-grey-light">{{$status['name']}}</td>
          <td class="py-4 px-6 border-b border-grey-light flex ">
            <a href="{{route('admin.Statuses.edit',$status['id'])}}"  id="edite" class="text-grey-lighter font-bold py-1 px-3 rounded text-xs bg-green hover:bg-green-800 ">Edit</a>
            
            <form action= "{{route('admin.Statuses.destroy',$status['id'])}}" method="post" >
              @csrf
              @method('delete')
              <button type="submit" class="text-red-600 font-bold py-1 px-3 rounded text-xs bg-blue hover:bg-blue-dark">delete</button>
            </form>
          </td>
         
        </tr>
    @endforeach
        
     
       
      </tbody>
    </table>
  </div>
</div>

@endif


</x-admin-layout>